[package]
name = "xanthidae"
version = "1.0.0"
authors = [
    "Marco Erdmann",
    "Anne von Raven",
    "Frank Schmitt"
]
publish = false
edition = "2018"

[lib]
name = "rustplugin"
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "commdlg", "shobjidl", "shobjidl_core", "combaseapi", "objbase", "winbase"] }
scopeguard = "1.1.0"
lazy_static = "1.4.0"
log = "0.4.14"
simplelog = "0.10.0"
chrono = "0.4.19"
regex = "1.4.5"
indoc = "1.0.3"
