= SYNOPSIS

A Rust-based plugin for the https://www.allroundautomations.com/products/pl-sql-developer/[PL/SQL Developer] IDE. Main feature is the generation of migration scripts for https://flywaydb.org/[Flyway].

In case you're wondering about the name - https://en.wikipedia.org/wiki/Xanthidae[Xanthidae] is a family of crabs, and therefore, choosing that name for a Rust-based plugin seemed kind of natural (also, all the good names were already taken :-)

= BUILD

== Windows
[source,shell]
---------------
cargo build
---------------

== Linux
There are several ways to compile the plugin on Linux. We recommend using cross. You can obtain it via
[source,shell]
---------------
cargo install cross
---------------

Afterwards, building the plugin is pretty straightforward:

[source,shell]
---------------
cross build --target x86_64-pc-windows-gnu
---------------

If the build was successful, the output can be found in target/x86_64-pc-windows-gnu/debug.


= INSTALL
== DIRECT INSTALLATION
[source,shell]
---------------
copy xanthidae.dll c:\program files\plsql developer <version>\plugins\
---------------

== SYMLINK (for developers)
If you want to avoid having to copy the file every time you build a new version, you can use a symbolic link instead:
[source,shell]
--------------
mklink <version>\plugins\xanthidae.dll xanthidae.dll
--------------
*CAVEAT* If you use this approach, cargo build will fail if a PL/SQL Developer instance is running (because the output file is locked).


= DEBUG
For debugging, you can use e.g. Python to check whether the DLL can be loaded successfully:

[source,shell]
---------------
from ctypes import *
print(cdll.xanthidae.IdentifyPlugIn(7))
---------------

= RUN
[source,shell]
---------------
plsqldev.exe /debugplugins
---------------

(this will create a file %appdata%/PLSQL Developer <version>/debug.txt containing helpful messages for debugging)

= LICENSE
Apache 2.0 (see LICENSE file for details)
